### ISSUE TITLE
Twitter crawling appears to have broken

### ISSUE THREAD

**Issue by theodric** [visualbasic6/chatter#1]
Judging by the most recent date in my DB entries, Chatter's Twitter crawling stopped working on 3 June. I have updated to the latest client, but the issue persists. I have also tried starting over with a new instance of the bot on a different computer, to no effect: the Twitter DB is not updated with new entries for any keyword. When I ran a query manually for one of my keywords using the Twitter URL provided in the readme.md, normal and recent results appeared in my browser. I'm not sure what happened to cause this issue, and since I don't have a license for the HTTP control, I'm not able to build the app to troubleshoot it further.
![well_crap](https://user-images.githubusercontent.com/144880/84302602-db6ac980-ab55-11ea-8fe1-0ce9e0a12c83.png)

**Comment by visualbasic6** [comment]
yeah i'll do this soon if someone else doesn't

probably a quick bugfix

and i hear you re: license key issues. might switch to winhttp or something

**Comment by theodric** [comment]
I poked at it a bit further, mitmproxy'd and Wiresharked, and found this page in one of reassembled chunks. Might be a red herring but I figured I'd mention it.
![20200623_114734](https://user-images.githubusercontent.com/144880/85389222-6e890380-b547-11ea-92b3-510ebc841a84.jpg)

**Comment by visualbasic6** [comment]
nice work. yeah that can probably be fixed. it would be interesting to mitm different request headers or see if it's some type of erroneous device id script misfiring on chatter

**Comment by visualbasic6** [comment]
twitter is fixed

@theodric turns out it wasn't an issue of browser support. now when chatter loads it sends `authorization: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA` in a request to `https://api.twitter.com/1.1/guest/activate.json` which returns `x-guest-token`. this is the token we now require. the start button becomes visible upon mouseover when this process is complete; which only takes a few seconds.
